cookie:
  expiry_days: 1
  key: random_signature_key
  name: random_cookie_name
credentials:
  usernames:
    admin:
      email: 100472175@alumnos.uc3m.es
      name: "Eduardo Alarc\xF3n"
      password: $2b$12$fpo4PLSoGnWffLw3UJXPeuB0hf/Ah9RIV34SAtegtL86JXmqZrLZG
      rol: escuela
    c_buendia:
      email: 100429669@alumnos.uc3m.es
      name: "Carlos Buend\xEDa Merino"
      password: $2b$12$3wHJzKnYLtW7tR3UWHadaukU/s4WvIbKCPYkJUUISfxCNIXqM.1yy
      rol: despacho
    c_calles:
      email: 100522525@alumnos.uc3m.es
      name: Carlos Calles Gomez
      password: $2b$12$Y4LiP.jBe3fjh9zidXtMIeVnxa7mhDo6Go7.IO6I/UhtkpV7lhWSi
      rol: despacho
    c_carrion:
      email: 100429532@alumnos.uc3m.es
      name: "Carmen Carri\xF3n Galv\xE1n"
      password: $2b$12$MFhuGtdb7Eumx/vmJZufJ.AzhCBX3ab2uglZHWWYa7AWJPjfuzv5q
      rol: despacho
    c_zaragoza:
      email: 100451145@alumnos.uc3m.es
      name: Carlos Zaragoza Arocha
      password: $2b$12$nDyxso0eBOCqYTpg4LMQKu/XpLrZRMoEXLcOadyWor45VNMEQdLdm
      rol: despacho
    e_alarcon:
      email: 100472175@alumnos.uc3m.es
      name: "Eduardo Alarc\xF3n Navarro"
      password: $2b$12$GaOahcmscoISAnsNvkdrMeudoTUSdoqLv3Qk1xr2SkwB0LkLiU8XW
      rol: despacho
    e_peres:
      email: 100429483@alumnos.uc3m.es
      name: "Elena P\xE9rez Manzano"
      password: $2b$12$TuDKf5./vrJtDTUKOSl/SOblwNyyAVC62V7Q/CrXQUoRiH345Dxwi
      rol: despacho
    j_lazaro:
      email: 100452172@alumnos.uc3m.es
      name: "Jorge L\xE1zaro Ruiz"
      password: $2b$12$21m6tWYjwUkzCyW53nESJ.cFDt/bjQtf8yX3PmCKRYpHyK0O52PNy
      rol: despacho
    j_martin:
      email: 100429437@alumnos.uc3m.es
      name: "Juan Mart\xEDn Hern\xE1ndez"
      password: $2b$12$GxvkFejMd1UBKM1tl3pnV.oQalvv2rzufYfrk/9BdvLavl8k/WAwq
      rol: despacho
    l_belizon:
      email: 100452273@alumnos.uc3m.es
      name: "Laura Beliz\xF3n Merch\xE1n"
      password: $2b$12$UKcbgje7JEc0jheKsoGdtuvRCt0b5rIZJ0w9p3Ds.TQxC.9KMCiLi
      rol: escuela
    l_duran:
      email: 100429460@alumnos.uc3m.es
      name: "Luc\xEDa Dur\xE1n Mart\xEDn"
      password: $2b$12$1G1gc9cXnTbnUwYJDOOMiOFbykRsbuqN7rmoqgUZljiIIIJrEFcRa
      rol: despacho
    m_gomez:
      email: 100472310@alumnos.uc3m.es
      name: "Manuel G\xF3mez-Plana Rodr\xEDguez"
      password: $2b$12$QpysMZ7bx/I17xwUGXYx8uDD./GWNSi9m1HpahW4lOUumWnz22c3u
      rol: escuela
    m_sanchez:
      email: 100365674@alumnos.uc3m.es
      name: "Mart\xEDn S\xE1nchez Arranz"
      password: $2b$12$jg7NvUCPcPw0Vw3oVOPxz./l5z87/ZwXAA7hGyIgjCiWgN6N1gN9i
      rol: despacho
    m_scarpa:
      email: 100451824@alumnos.uc3m.es
      name: "Mat\xEDas Scarpa Gonz\xE1lez"
      password: $2b$12$ug1ckwybFw9VRM8UDCDpYea7r2sGrsGX1q.YAyktsb2NKkqoTXZt6
      rol: despacho
    n_valverde:
      email: 100522796@alumnos.uc3m.es
      name: Nadia Valverde Roscan
      password: $2b$12$J/WbtP1JT1NaGNMCwcIBcOn/pVnnGDa8ieMVGHEVhHSkEfv0qrbrW
      rol: despacho
    p_paredes:
      email: 100429542@alumnos.uc3m.es
      name: Pablo Paredes Romero
      password: $2b$12$BkIPvly6zJ20vIoHYJhGKujjvYzhojoYulHf0XO6bYTZL.71///bK
      rol: despacho
    s_ayala:
      email: 100495832@alumnos.uc3m.es
      name: Salvador Ayala Iglesias
      password: $2b$12$9/R4HaWMnQC0OQQC/PJrqOnQfUDusYlR2UYmAcZiA7zaOciseBVrS
      rol: escuela
    s_pantoja:
      email: 100416753@alumnos.uc3m.es
      name: Sofia Pantoja Cano
      password: $2b$12$wDsuVF6n3guAv6/1xTzlnOqfU6oAvyFrt8ixflX01kQCUbN4W7sZG
      rol: despacho
preauthorized:
  emails:
  - edu@gmail.com
reset_password:
  password: cb74921ea6811ce65b5a18eab2b7e289
